
name:                         onDeploy Databricks
on:                             
  workflow_dispatch:
    inputs:
      script_language: 
        type: choice
        description: Python or Bash (Databricks API)
        options:
          - python
          - bash
        default: python

jobs:
  ReuseableMatrixJobForDeployment:
    name:                     Master Deployment
    strategy:
      matrix:
        targetEnvironment:    [ development, uat] # development, uat, production 
    uses:                     ./.github/workflows/taskDatabricks.yaml
    with:
      ENVIRONMENT:            ${{ matrix.targetEnvironment }}
      DBX_REPO_BRANCH:        'main'
      SCRIPT_LANGUAGE:        ${{ github.event.inputs.script_language }}
      DevOps_Agent:           GitHub
    secrets:
      ARM_CLIENT_ID:          ${{ secrets.ARM_CLIENT_ID }}    
      ARM_CLIENT_SECRET:      ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID:          ${{ secrets.ARM_TENANT_ID }}
      PAT_GITHUB:             ${{ secrets.PAT_GITHUB }}
      
  



      

  
  
